parameters:
- name: "environment"
  type: string
- name: 'namespace'    
  type: string

jobs:
- deployment: Deploy
  variables:
  - name: ecrImageName
    value: "$[stageDependencies.Build.Build.outputs['ECRImageOutputStep.ecrImage']]"
  pool:
    vmImage: 'ubuntu-20.04'
  environment: ${{parameters.environment}}
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: 'drop'
        - task: CmdLine@2
          inputs:
            script: echo "Deploying image $(ecrImageName)"

        - task: Kubernetes@1
          displayName: kubectl prepare namespace yaml
          inputs:
            connectionType: Kubernetes Service Connection
            kubernetesServiceEndpoint: $(kubernetesServiceConnection)
            command: create
            arguments: -n $(namespace) --dry-run=client -o yaml > ns.yaml
            useConfigurationFile: false

        - task: Kubernetes@1
          displayName: kubectl create namespace
          inputs:
            connectionType: Kubernetes Service Connection
            kubernetesServiceEndpoint: $(kubernetesServiceConnection)
            command: apply
            useConfigurationFile: true
            configuration: ns.yaml

        - task: KubernetesManifest@0
          inputs:
            action: 'deploy'
            kubernetesServiceConnection: $(kubernetesServiceConnection)
            namespace: '$(namespace)'
            manifests: '$(Pipeline.Workspace)/drop/k8s/manifests/deployment.yaml'
            containers: '$(ecrImageName)'
