parameters:
- name: "environment"
  type: string

jobs:
- deployment: Deploy
  variables:
  - name: ecrImageName
    value: "$[stageDependencies.Build.Build.outputs['ECRImageOutputStep.ecrImage']]"
  pool:
    vmImage: 'ubuntu-20.04'
  environment: ${{parameters.environment}}
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: 'drop'
        - task: CmdLine@2
          inputs:
            script: echo "Deploying image $(ecrImageName)"

        - task: KubernetesManifest@0
          inputs:
            action: 'deploy'
            kubernetesServiceConnection: $(kubernetesServiceConnection)
            namespace: '$(namespace)'
            manifests: '$(Pipeline.Workspace)/drop/k8s/manifests/deployment.yaml'
            containers: '$(ecrImageName)'
