parameters:
- name: "environment"
  type: string
- name: 'namespace'    
  type: string

jobs:
- deployment: Deploy
  variables:
  - name: ecrImageName
    value: "$[stageDependencies.Build.Build.outputs['ECRImageOutputStep.ecrImage']]"
  - name: namespace
    value: $[replace(parameters.namespace, '/', '-')]
  pool:
    vmImage: 'ubuntu-20.04'
  environment: ${{parameters.environment}}
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: 'drop'
        - task: CmdLine@2
          inputs:
            script: echo "Deploying image $(ecrImageName)"

        - task: Kubernetes@1
          displayName: 'Create a new namespace for the pull request'
          inputs:
            connectionType: Kubernetes Service Connection
            kubernetesServiceEndpoint: $(kubernetesServiceConnection)
            command: apply
            useConfigurationFile: true
            inline: '{ "kind": "Namespace", "apiVersion": "v1", "metadata": { "name": "$(namespace)" }}'

        - task: KubernetesManifest@0
          inputs:
            action: 'deploy'
            kubernetesServiceConnection: $(kubernetesServiceConnection)
            namespace: $(namespace)
            manifests: '$(Pipeline.Workspace)/drop/k8s/manifests/deployment.yaml'
            containers: '$(ecrImageName)'
