trigger:
  batch: false

  branches:
    exclude:
    - 'refs/branches/*'

  tags:
    include:
    - v*

pr: none
  

variables:
  - name: tag
    value: '$(Build.SourceBranchName)'
  - name: semanticVersion
    value: $[ replace(variables['Build.SourceBranchName'], 'v', '') ]
  - group: devops-framework-backend-global

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - template: templates/build.yaml
    parameters:
      test: false

- stage: Prod
  displayName: 'Deploy to the Prod environment'
  variables:
  - group: devops-framework-backend-prod
  - name: ecrImageName
    value: "$[stageDependencies.Build.Build.outputs['ECRImageOutputStep.ecrImage']]"
  condition: and(
    succeeded(),
    startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    )
  dependsOn: Build
  jobs:
  - template: templates/deploy-kubernetes.yaml
    parameters:
      environment: prod
