trigger:
  batch: true
  branches:
    include:
    - main
    - release
  paths:
    exclude:
    - pipelines/*
    - '*.md'
    - .github/workflows
pr:
  autoCancel: true # indicates whether additional pushes to a PR should cancel in-progress runs for the same PR. Defaults to true
  branches:
    include:
    - main
  drafts: false # whether to build draft PRs, defaults to true
  paths:
    exclude:
    - pipelines/*
    - '*.md'
    - .github/workflows

parameters:
- name: test
  displayName: Run Tests?
  type: boolean
  default: true

variables:
  - name: tag
    value: '$(Build.BuildId)'
  - group: devops-framework-backend-global

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - template: templates/build.yaml
    parameters:
      test: ${{ parameters.test }}

- ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
  - stage: DeployPR
    displayName: 'Deploy to the temporary PR environment'
    dependsOn: Build
    variables:
      - name: namespace
        value: $[format('{0}-{1}', replace(variables['System.PullRequest.SourceBranch'], '/', '-'), variables['System.PullRequest.PullRequestNumber'])]

    jobs:
    - template: templates/deploy-kubernetes-pr.yaml
      parameters:
        environment: pr

- ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranchName'], 'main')) }}:
  - stage: DeployDev
    displayName: 'Deploy to the Dev environment'
    dependsOn: Build
    variables:
    - group: devops-framework-backend-dev
    jobs:
    - template: templates/deploy-kubernetes.yaml
      parameters:
        environment: dev

- ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranchName'], 'release')) }}:
  - stage: DeployPreprod
    displayName: 'Deploy to the Preprod environment'
    dependsOn: Build
    variables:
    - group: devops-framework-backend-preprod
    jobs:
    - template: templates/deploy-kubernetes.yaml
      parameters:
        environment: preprod
