trigger:
  batch: true
  branches:
    include:
    - main
    - release
  paths:
    exclude:
    - pipelines/*
    - '*.md'

parameters:
- name: test
  displayName: Run Tests?
  type: boolean
  default: true

variables:
  - name: tag
    value: '$(Build.BuildId)'
  - group: devops-framework-backend-global

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - template: templates/build.yaml
    parameters:
      test: ${{ parameters.test }}

- stage: PR
  displayName: 'Deploy to the temporary PR environment'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
  dependsOn: Build
  jobs:
  - template: templates/deploy-kubernetes-pr.yaml
    parameters:
      environment: pr
      namespace: '$(System.PullRequest.SourceBranch)-$(System.PullRequest.PullRequestNumber)'

- stage: Dev
  displayName: 'Deploy to the Dev environment'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranchName'], 'main'))
  dependsOn: Build
  jobs:
  - template: templates/deploy-kubernetes.yaml
    parameters:
      variableGroup: devops-framework-backend-dev
      environment: dev

- stage: Preprod
  displayName: 'Deploy to the Preprod environment'
  condition: and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranchName'], 'release'))
  dependsOn: Build
  jobs:
  - template: templates/deploy-kubernetes.yaml
    parameters:
      variableGroup: devops-framework-backend-preprod
      environment: preprod
